/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterfaz;

import CapaDatos.ClsConexion;
import java.io.File;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fundamentos DS
 */
public class WinInicio extends javax.swing.JFrame {

    ClsConexion base;
    String BasedeDatos;
    String nP,aC,dC,tC;
    int clvC;
    float pP;
    public WinInicio() {
        initComponents();
        ArchBd.setVisible(false);
        PnlAgenda.setVisible(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlAgenda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtDir = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtApell = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        BtnSigui = new javax.swing.JButton();
        BtnAnt = new javax.swing.JButton();
        TxtTelf = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        BtnGuar = new javax.swing.JButton();
        BtnMod = new javax.swing.JButton();
        BtnBorr = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        BtnElimi = new javax.swing.JButton();
        BtnNuevo = new javax.swing.JButton();
        BtnConsult = new javax.swing.JButton();
        BtnActu = new javax.swing.JButton();
        ArchBd = new javax.swing.JFileChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlAgenda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PnlAgenda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Dirección");
        PnlAgenda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 60, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("AGENDA");
        PnlAgenda.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 80, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nombre");
        PnlAgenda.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 50, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Teléfono");
        PnlAgenda.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 60, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Apellido");
        PnlAgenda.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 60, 20));

        TxtDir.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TxtDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDirActionPerformed(evt);
            }
        });
        PnlAgenda.add(TxtDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 150, 20));

        TxtNombre.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });
        PnlAgenda.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 150, 20));

        TxtApell.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TxtApell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtApellActionPerformed(evt);
            }
        });
        PnlAgenda.add(TxtApell, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 150, 20));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnSigui.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnSigui.setText("Siguiente");
        BtnSigui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguiActionPerformed(evt);
            }
        });
        jPanel4.add(BtnSigui, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        BtnAnt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnAnt.setText("Anterior");
        BtnAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAntActionPerformed(evt);
            }
        });
        jPanel4.add(BtnAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        PnlAgenda.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 240, 40));

        TxtTelf.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TxtTelf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelfActionPerformed(evt);
            }
        });
        PnlAgenda.add(TxtTelf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 150, 20));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnGuar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnGuar.setText("Guardar");
        BtnGuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnGuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 10, 100, -1));

        BtnMod.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnMod.setText("Modificar");
        BtnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModActionPerformed(evt);
            }
        });
        jPanel2.add(BtnMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, -1));

        BtnBorr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnBorr.setText("Borrar");
        BtnBorr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrActionPerformed(evt);
            }
        });
        jPanel2.add(BtnBorr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, -1));

        PnlAgenda.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 120, 100));

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnElimi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnElimi.setText("Eliminar");
        BtnElimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnElimiActionPerformed(evt);
            }
        });
        jPanel3.add(BtnElimi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, -1));

        BtnNuevo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnNuevo.setText("Nuevo");
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });
        jPanel3.add(BtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 10, 100, -1));

        BtnConsult.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnConsult.setText("Consultar");
        BtnConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultActionPerformed(evt);
            }
        });
        jPanel3.add(BtnConsult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, -1));

        BtnActu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnActu.setText("Actuaizar");
        BtnActu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActuActionPerformed(evt);
            }
        });
        jPanel3.add(BtnActu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, -1));

        PnlAgenda.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 120, 130));

        getContentPane().add(PnlAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 560, 270));

        ArchBd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchBdActionPerformed(evt);
            }
        });
        getContentPane().add(ArchBd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 530, 340));

        jMenu1.setText("Base de datos");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Agenda");

        jMenuItem3.setText("Entrar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       ArchBd.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ArchBdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchBdActionPerformed
        File f=ArchBd.getSelectedFile();
        BasedeDatos=f.getAbsolutePath();
        ArchBd.setVisible(false);
        base=new ClsConexion(BasedeDatos);
    }//GEN-LAST:event_ArchBdActionPerformed

    private void TxtDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDirActionPerformed

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    private void TxtApellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtApellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtApellActionPerformed

    private void TxtTelfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelfActionPerformed

    private void BtnGuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuarActionPerformed

    private void BtnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnModActionPerformed

    private void BtnBorrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBorrActionPerformed

    private void BtnElimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnElimiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnElimiActionPerformed

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void BtnConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnConsultActionPerformed

    private void BtnActuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnActuActionPerformed

    private void BtnAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAntActionPerformed
        try {
           
            base.anterior();
            
            TxtNombre.setText(base.registros().getString("nombre"));

            TxtApell.setText(base.registros().getString("apellido"));
            TxtDir.setText(base.registros().getString("direccion"));
            clvC = base.registros().getInt("Id");
        } catch (SQLException ex) {
            Logger.getLogger(WinInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnAntActionPerformed

    private void BtnSiguiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguiActionPerformed
        try {
           
            base.siguiente();
            TxtNombre.setText(base.registros().getString("nombre"));
            TxtApell.setText(base.registros().getString("apellido"));
            TxtDir.setText(base.registros().getString("direccion"));
            clvC = base.registros().getInt("Id");
        } catch (SQLException ex) {
            Logger.getLogger(WinInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnSiguiActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        PnlAgenda.setVisible(true);
        ArchBd.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser ArchBd;
    private javax.swing.JButton BtnActu;
    private javax.swing.JButton BtnAnt;
    private javax.swing.JButton BtnBorr;
    private javax.swing.JButton BtnConsult;
    private javax.swing.JButton BtnElimi;
    private javax.swing.JButton BtnGuar;
    private javax.swing.JButton BtnMod;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JButton BtnSigui;
    private javax.swing.JPanel PnlAgenda;
    private javax.swing.JTextField TxtApell;
    private javax.swing.JTextField TxtDir;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtTelf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
